name: ${PROJECT_NAME}

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - AUTH_TRUST_HOST=true
      - AUTH_SECRET=${AUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - project-net
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  project-net:
    external: true
    name: ${PROJECT_NAME}-project-net